name: "CI"

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
      - develop

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 18.18.0 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node.js ${{ matrix.node-version }} version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: oven-sh/setup-bun@v2

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('bun.lockb') }}
          restore-keys: ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.node-version }}-

      - name: Install dependency
        if: steps.cache.outputs.cache-hit != 'true'
        run: bun install

      - name: build
        run: bun run build

      - uses: mshick/add-pr-comment@v1
        if: ${{ success() }}
        with:
          message: |
            ✨ CI success.
            - OS: ${{ matrix.os }}
            - node.js: v${{ matrix.node-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: true
